//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLASS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLASS()
        {
            this.CLASS_SCHEDULE = new HashSet<CLASS_SCHEDULE>();
        }
    
        public int Class_ID { get; set; }
        public string Class_Name { get; set; }
        public string Description { get; set; }
        public int Instructor_ID { get; set; }
        public int Duration_Minutes { get; set; }
        public int Max_Capacity { get; set; }
        public string Difficulty_Level { get; set; }
        public string Category { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
    
        public virtual STAFF STAFF { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLASS_SCHEDULE> CLASS_SCHEDULE { get; set; }
    }
}
