//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class EQUIPMENT
    {
        public int Equipment_ID { get; set; }
        public string Equipment_Name { get; set; }
        public string Equipment_Type { get; set; }
        public int Facility_ID { get; set; }
        public Nullable<System.DateTime> Purchase_Date { get; set; }
        public Nullable<System.DateTime> Last_Maintenance { get; set; }
        public Nullable<System.DateTime> Next_Maintenance { get; set; }
        public string Status { get; set; }
        public string Serial_Number { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
    
        public virtual FACILITY FACILITY { get; set; }
    }
}
