//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACILITY_RESERVATION
    {
        public int Reservation_ID { get; set; }
        public int Facility_ID { get; set; }
        public int Member_ID { get; set; }
        public System.DateTime Reservation_Date { get; set; }
        public System.TimeSpan Start_Time { get; set; }
        public System.TimeSpan End_Time { get; set; }
        public string Purpose { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
    
        public virtual FACILITY FACILITY { get; set; }
        public virtual MEMBER MEMBER { get; set; }
    }
}
