//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACILITY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FACILITY()
        {
            this.CLASS_SCHEDULE = new HashSet<CLASS_SCHEDULE>();
            this.EQUIPMENTs = new HashSet<EQUIPMENT>();
            this.FACILITY_RESERVATION = new HashSet<FACILITY_RESERVATION>();
        }
    
        public int Facility_ID { get; set; }
        public string Facility_Name { get; set; }
        public string Facility_Type { get; set; }
        public int Capacity { get; set; }
        public Nullable<int> Floor_Number { get; set; }
        public string Equipment_Available { get; set; }
        public Nullable<decimal> Hourly_Rate { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLASS_SCHEDULE> CLASS_SCHEDULE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EQUIPMENT> EQUIPMENTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACILITY_RESERVATION> FACILITY_RESERVATION { get; set; }
    }
}
