//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEMBERSHIP_TYPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MEMBERSHIP_TYPE()
        {
            this.MEMBERs = new HashSet<MEMBER>();
        }
    
        public int Type_ID { get; set; }
        public string Type_Name { get; set; }
        public string Description { get; set; }
        public decimal Monthly_Fee { get; set; }
        public Nullable<int> Duration_Months { get; set; }
        public Nullable<int> Max_Classes { get; set; }
        public Nullable<bool> Facility_Access { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEMBER> MEMBERs { get; set; }
    }
}
