//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEMBER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MEMBER()
        {
            this.FACILITY_RESERVATION = new HashSet<FACILITY_RESERVATION>();
            this.REGISTRATIONs = new HashSet<REGISTRATION>();
        }
    
        public int Member_ID { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public System.DateTime Date_Of_Birth { get; set; }
        public Nullable<System.DateTime> Join_Date { get; set; }
        public int Membership_Type_ID { get; set; }
        public string Status { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZIP_Code { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACILITY_RESERVATION> FACILITY_RESERVATION { get; set; }
        public virtual MEMBERSHIP_TYPE MEMBERSHIP_TYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REGISTRATION> REGISTRATIONs { get; set; }
    }
}
