//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecCenter
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class group8Entities : DbContext
    {
        public group8Entities()
            : base("name=group8Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CLASS> CLASSes { get; set; }
        public virtual DbSet<CLASS_SCHEDULE> CLASS_SCHEDULE { get; set; }
        public virtual DbSet<EQUIPMENT> EQUIPMENTs { get; set; }
        public virtual DbSet<FACILITY> FACILITies { get; set; }
        public virtual DbSet<FACILITY_RESERVATION> FACILITY_RESERVATION { get; set; }
        public virtual DbSet<MEMBER> MEMBERs { get; set; }
        public virtual DbSet<MEMBERSHIP_TYPE> MEMBERSHIP_TYPE { get; set; }
        public virtual DbSet<REGISTRATION> REGISTRATIONs { get; set; }
        public virtual DbSet<STAFF> STAFFs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
